default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: mutants_development

test:
  <<: *default
  database: mutants_test

production:
  adapter: postgresql
  pool: 5
  url: <%= ENV['DATABASE_URL'] =>  

